[German] Review of 2022 Wordle sentence_translations.json
3b1b/captions pull request #115
Opened 2024-02-05 18:56 UTC by Thadaeus

Hello, I have revised the first 815 lines and changed a few things. If someone who is a native German speaker could check my changes and translations, I would be very grateful.

2024-02-11 05:50 UTC, zsawyer requested changes
Changes reviewed. Some changes required. Native speaker here.

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Das ist im Moment eine Art Unentschieden zwischen ihnen, also nehme ich an einfach weil es alphabetisch ist, dass es shard ist.",
```suggestion
  "translatedText": "Das ist im Moment eine Art Unentschieden zwischen ihnen, ich nehme also an, dass er shard nimmt, weil er alphabetisch vorgeht.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "welche Hurra, tatsächlich die Antwort ist.",
```suggestion
  "translatedText": "was, hurra, tatsächlich die Antwort ist.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Falls Sie sich fragen, ob das irgendetwas bringt: Ich habe gehört, wie eine Person es so ausgedrückt hat, dass bei wordle vier gleich Par und drei gleich Birdie sind.",
```suggestion
  "translatedText": "Falls Sie sich fragen, ob das irgendetwas gebracht hat: Ich habe gehört, wie eine Person es so ausgedrückt hat, dass bei wordle vier Züge einem Par und drei einem Birdie entsprechen.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Und wie ich schon sagte, es ist eigentlich ein Ausrede für eine Lektion in Informationstheorie.",
```suggestion
  "translatedText": "Und wie ich schon sagte, es ist eigentlich ein Vorwand für eine Lektion in Informationstheorie.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Der Gedanke ist, dass wenn man einen Buchstaben errät, diese dann grün oder gelb markiert werden. Das fühlt sich immer gut an",
```suggestion
  "translatedText": "Der Gedanke ist, dass wenn man einen Buchstaben errät, dieser dann grün oder gelb markiert wird. Das fühlt sich immer gut an",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Aber selbst wenn du in diesen Fällen kein richtigen Buchstaben erräts und nur graue Buchstaben bekommst, erhälst du dennoch viele Informationen, da es ziemlich selten ist, ein Wo
```suggestion
  "translatedText": "Aber selbst wenn du in diesen Fällen kein richtigen Buchstaben errätst und nur graue Buchstaben bekommst, erhältst du dennoch viele Informationen, da es ziemlich selten ist, ein Wort zu finden, das keinen dieser Buchstaben enthält.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Es gibt eine Liste von Wörtern, die Sie eingeben können und die als gültige Vermutungen gelten und die nur etwa 13.000 Wörter lang ist.",
```suggestion
  "translatedText": "Es gibt eine Liste von Wörtern, die man eingeben kann und die als gültige Vermutungen gelten. Diese ist in etwa 13.000 Wörter lang.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Und tatsächlich gibt es noch eine weitere Liste mit rund 2300 Wörtern, die mögliche Antworten darstellt.",
```suggestion
  "translatedText": "Und tatsächlich gibt es noch eine weitere Liste mit rund 2300 Wörtern, die mögliche Antworten darstellen.",
```

Darstellen refers to Antworten and not Liste, Antworten isi plural so we use plural form of the verb.

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Aber was ich gerne machen würde, unsere Herausforderung für dieses Projekt ist zu sehen, ob wir ein  Programm schreiben können, das Wordle löst, ohne vorheriges Wissen über diese
```suggestion
  "translatedText": "Aber was ich gerne als unsere Herausforderung für dieses Projekt machen würde ist zu sehen, ob wir ein Programm schreiben können, das Wordle löst, ohne dieses vorherige Wissen aus der Liste mit einzubeziehen.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Du können also jederzeit nachschauen, wie die Antwort für morgen lautet.",
```suggestion
  "translatedText": "Du könntest also jederzeit nachschauen, wie die Antwort für morgen lautet.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Nun, der Grund, warum er sagte, dass er dieses unwahrscheinliche W mag, ist die Tatsache, dass das W sehr unwahrscheinlich ist. Ist das W im Wort enthalten und man hats erraten,
```suggestion
  "translatedText": "Nun, der Grund, warum er sagte, dass er dieses unwahrscheinliche W mag, ist die Tatsache, dass das W sehr unwahrscheinlich ist. Ist das W im Wort enthalten und man hat es erraten, fühlt es sich einfach großartig an.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Aber zumindest für unseren ersten Versuch: Lasst uns annehmen, dass sie alle gleich wahrscheinlich sind, und verfeinern das dann etwas später.",
```suggestion
  "translatedText": "Aber zumindest für unseren ersten Versuch: Lass uns annehmen, dass sie alle gleich wahrscheinlich sind, und wir verfeinern das dann etwas später.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Am Wahrscheinlichsten ist es, dass du nur Grautöne erhälst.",
```suggestion
  "translatedText": "Am Wahrscheinlichsten ist es, dass du nur Graue erhältst.",
```

2024-02-11 05:50 UTC, zsawyer commented on 2022/wordle/german/sentence_translations.json
> +  "translatedText": "Oder wenn wir uns etwas weiter nach rechts wagen, vielleicht kommen wir dann bis hierher.",
```suggestion
  "translatedText": "Oder wenn wir uns etwas weiter nach links wagen, vielleicht kommen wir dann bis hierher.",
```

2024-02-28 04:40 UTC, 3b1b commented
Thanks for the review, for convenience I added it in https://github.com/3b1b/captions/pull/206

2024-02-28 04:40 UTC, closed without merging