Hungarian translation of the essence of calculus video
3b1b/captions pull request #36
Opened 2024-02-04 04:41 UTC by homok43

This translation was intended to be a quick suffix-fixing one, but instead it quickly went off the rails :D

### Problems of the AI translation

Similarly to #13, the problem of the AI translating "you" as a formal you comes up in Hungarian as well, as well the problem of out of context words and mistranslated technical concepts. However, sometimes words, or even whole sentence clauses are omitted. Many sentences range from unnatural to incomprehensible. 

Out of curiosity I tried feeding a couple strings to DeepL as proposed in #10 and it was better but wasn't quite there yet (we probably can't expect that from any tool tbh). In the end, I felt like there was something off in almost all of the sentences, so I corrected the whole thing as best as i could.

### Dev experience

It wasn't absurd to edit a raw JSON file by hand, but for broader community contribution I believe it would be better to have an interface that only allows access to the relevant data, that way more non-technical people could contribute. Some kind of proofreading or peer review/voting for submitted fixes is also something that would be great to have in my opinion.

### Questions

If these subtitles are going to be used for generating audio tracks, how should notation be transcribed in cases where writing it as you say it would negatively affect reading? (For example dA for small change in area could be pronounced as "daa" by the AI voice, but writing it any other way would cause a mismatch between the video and the subtitles). Maybe an optional pronunciation override?

2024-02-05 12:23 UTC, MrExpertGitHub requested changes
Kijavítottam néhány matematikai pontatlanságot
-Kaszap Máté

2024-02-05 12:23 UTC, MrExpertGitHub commented on 2017/essence-of-calculus/hungarian/sentence_translations.json
> +  "translatedText": "Tudjuk, hogy az x2 görbéje alatti területet adja meg egy rögzített bal pont és egy változó jobb oldali pont között, de nem tudjuk, mi az. ",
```suggestion
  "translatedText": "Tudjuk, hogy az x négyzet függvény görbéje alatti területet adja meg egy rögzített bal pont és egy változó jobb oldali pont között, de nem tudjuk, mi az. ",
```

2024-02-05 14:56 UTC, 3b1b commented
Good to know that DeepL is a better starting point.

As to how the TTS handles it, in a week or two we can make a few samples for you to see what it does by default, and perhaps that will inform how things should be corrected.

Is this one good to merge?

2024-02-05 15:44 UTC, homok43 commented on 2017/essence-of-calculus/hungarian/description.json
> +  "translatedText": "Milyen érzés lehet feltalálni a kalkulust?",
Azért maradtam a kalkulusnál, mert szerintem az analízis kicsit szigorúbbnak érződik mint ennek a sorozatnak a geometriai és infinitezimálisos megközelítése, legalábbis az elején, a 7-esnél már elég formális. Itthon se annyira ismeretlen, sok egyetemi kurzus is kalkulusként van elnevezve, meg persze ott van pl a Thomas-féle kalkulus könyv is. De igazad van, meg nekem is jobban tetszik az analízis mint kifejezés :D

2024-02-05 16:07 UTC, MrExpertGitHub requested changes

2024-02-05 16:07 UTC, MrExpertGitHub commented on 2017/essence-of-calculus/hungarian/sentence_translations.json
> +  "translatedText": "A kalkulusnak sok szabálya és képlete van, amelyeket gyakran megjegyzendő dolgokként mutatnak be. ",
```suggestion
  "translatedText": "Az analitikának sok szabálya és képlete van, amelyeket gyakran megjegyzendő dolgokként mutatnak be. ",
```

2024-02-11 14:25 UTC, MrExpertGitHub approved these changes

2024-02-19 13:53 UTC, merged